//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skills
    {
        public byte Id { get; set; }
        public string Skill { get; set; }
        public Nullable<byte> Rate { get; set; }
    }
}
